### ISSUE TITLE
Main UI Concept

### ISSUE THREAD

**Issue by NoFear23m** [NoFear23m/LRPC_CommunityProject#6]
Ich habe mal ein Konzept erstellt. Es darf Diskutiert werden.
![MainUI_Concept](https://user-images.githubusercontent.com/15660141/63457306-17129680-c451-11e9-895b-f1bf8ee7fe82.jpeg)

**Comment by flori2212** [comment]
Find ich schon mal sehr gut.
Als Anmerkung würde ich sagen:
1. Die Produkte brauchen einen "Zähler" wie oft sie hunzugefügt wurden.
2. ICh denke in der Produktübersicht bekommt man alle relevanten Informationen rein, dann braucht man das Fenster unten rechts nicht mehr.
3. In Calculation was soll da stehen? Der Name, der Kunde, der Geammtpreis? An was hast du gedacht.

-Florian

**Comment by NoFear23m** [comment]
1.) JA, ich dachte da an den freien Platz rechts, da weis ich noch nicht wie das @asusdk handhabt mit Stückzahl, jetzt hat er gar keine drinnen. (Lade dir mal das WinForms Programm von Ihm, ich glaube im anderen Thread war das.
2.) Wenn man alle Informationen reinbekommt dann ja. Wenn es (ich habs ja jetzt mit Produktbild Designed) ohne Produktbild wird dann nicht. Wenn man alles an Infos reinbekommt kann mans weglassen, ist richtig.
3.) Schau dir die App von Ihm an, ich glaub 6-8 Werte sind es die da stehen werden.

Grüße

**Comment by flori2212** [comment]
3. Ach so, dort kommen die Calculation Results rein.
![image](https://user-images.githubusercontent.com/36850836/63458400-0a8f3d80-c453-11e9-9245-abcf8f3cb77f.png)

**Comment by NoFear23m** [comment]
Ja, so dachte ich es mir. So sieht man sofort das Ergebnis und muss nicht immer einen Dialog ausmachen. Platz ist ja genug ;-)

**Comment by NoFear23m** [comment]
> Man kann aktuell einfach ein Produkt 2mal hinzufügen, was aber keine schöne Lösung ist

Richtig, finde ich auch.

Aber jetzt soll ER sich auch melden. Hehe

**Comment by asusdk** [comment]
Sorry, das ich mich erst jetzt melde, musste mit einkaufen fahren und gerade noch kochen.
Das man ein Produkt mehrfach hinzufügen kann, ist definitiv gewünscht. Wenn ein Kunde beispielsweise 2mal das selbe Produkt leihen möchte, fügt man es halt 2x hinzu

Produktbilder wird es nicht geben, evtl. wenn es mit Bildern designd werden soll Einfach ein Icon mit dem Anfangsbuchstaben oder dergleichen ?

**Comment by flori2212** [comment]
> Evtl. kann der Bereich schlicht zur Anzeige der zuletzt berechneten Mietverträge verwendet werden ?

Klar, du kannst es nutzen für das was du brauchst, es war nur mal als Beispiel gedacht.

> ich denke da braucht man nicht mehrere offen haben können oder ?

Brauchen nicht, aber es würde ja auch nicht schaden. Und wäre bestimmt eine gute Übung.

> und zur Frage: In Calculation was soll da stehen?

Da finde ich eigentlich auch gut, wenn da auch die Ergebnisse schon stehen würden, dann braucht man (wie @NoFear23m schon geschrieben hat) kein extra Dialog.

**Comment by asusdk** [comment]
![Skizze](https://user-images.githubusercontent.com/54312862/63463572-b8074e80-c45d-11e9-85fd-076dec8f8a4d.jpg)

**Comment by asusdk** [comment]
So in etwa würd ich mir es vorstellen, ist zwar auch wieder mit 2 Listboxen, aber es ist schlicht, es ist funktional, kein SchnickSchnack, wenig benötigte Windows

Starten, producte wählen, Werte werden angezeigt, und Word-Datei kann befüllt werden

**Comment by NoFear23m** [comment]
Echt, so willst du es haben?

Ok, umso einfacher. 
Auch kein Menü oben und keine Statusbar??
Und wirklich ne Produktliste wo man die Produkte von einer in die andere klickt?

Okidoki

**Comment by asusdk** [comment]
Ja, im Prinzip reicht das doch vollkommen oder, Wofür würde ich hier denn ein Menü oder eine Statusbar benötigen ?

**Comment by NoFear23m** [comment]
Menü: Beenden, Einstellungen, About. Ach was schreib ich, noch nie ein Menü gesehen?

Statusbar ist jetzt nicht notwendig aber praktisch. Gut, gestrichen.

**Comment by asusdk** [comment]
Gesehen, schon, aber für Einstellungen reicht irgendwo ein Button in der UI, About brauch ich nicht (wenn da mal irgendwas nötig wäre (wofür?) reicht das als Fusszeile bei den Einstellungen)
Beenden, naaj dafür is ja das X oben rechts, auch unnötig dies mehrfach zu haben.

Ansich gefällt mir sogar mein altes Design am besten, nur das eben die Werte der Produkte als Labels angezeigt weden sieht halt schei... aus, und wie die Einträge in der Listbox aussehen würd ich halt gerne anpassen, aber das wars eigentlich, sonst find ich das alte design perfekt wie es ist, Simpel und funktional. Ich mag ehrlich gesagt diese ganzen heutzutage vorhanden überladenen Designs nicht sonderlich. Auch Metro-UI und co.

Es muss schlicht funktionieren, und man soll keinen Augenkrebs bekommen wenn man die UI sieht.
In theorie muss es auch nicht resizable sein, eine fixe Fenstergröße reicht auch aus. 

Ich weiss die WPF mach SEHR VIELES möglich. aber mir reicht im Prinzip das Binding (wenn ich es denn mal hinbekomme) und Die Templates (ListBox, TreeView), alles weitere ist gut zu wissen, wird aber wohl nie benötigt werden.

**Comment by NoFear23m** [comment]
Alles wie du willst, nur bei einer foxen Fenstergröße mach ich nicht mit. Das kommt mir nicht ins Haus. Das ist Pfusch. Schlecht Benutzerführung ist das eine aber Pfusch mach ich keinen, nur weil man zu faul ist. Nene

**Comment by asusdk** [comment]
Nicht falsch verstehen, (habe ich wohl falsch ausgedrückt) ich meinte jetzt im allgemeinen, das wir das hier so durchziehen, wie du es für angebracht hältst, habe ich ja schon mehrfach gesagt. Ich beziehe mich hier nur allgemein auf künftige Programme.  Und mit Faulheit hat es nur entfernt zu tun. Ich finde es selbst wenn es nur 1 Zeile Code wäre, einfach unnötig, generell, ich schreibe ja keine Programme wie ein Visual-Studio, ich schreibe winzige Tools, da reicht eine Fixe Größe vollkommen aus

**Comment by NoFear23m** [comment]
Weil du es nicht anders kennst. Wirst schon sehen. Gut. Jetzt machen wir hier schluss. Wir machen es wie deine Skizze. Jetzt kannst du im Forum mal schreiben wie DU ein ViewModel für den HauptView machen würdest. Bin gespannt.

**Comment by flori2212** [comment]
Ich finde es halt ein wenig schade, dass du so ein "simples" Anzeigefenster willst, wo du doch die Mögllichkeit hast, dir Funktionsweisen (wie z.B. eine Statusbar) einmal genau erklären zu lassen.
Auch die Tabs oben z.B. **stören** dein Programm ja nicht, würden aber einmal aufzeigen, wie man soetwas umsetzten würde.
Und glaube mir, so ein Produktverwaltungsfenster wie @NoFear23m vorgeschlagen hat, ist von der Benutzerfreundlichkeit besser.

Aber gut, wenn du meinst du brauchst das alles nicht, dann passt das.

PS: ein Menüband wird aber schon benötigt, um z.B. auf die Produkt hinzufügen-Seite zu wechseln.

**Comment by NoFear23m** [comment]
> ein Menüband wird aber schon benötigt, um z.B. auf die Produkt hinzufügen-Seite zu wechseln.
Bekommt er eh, ob er will oder nicht. Ist ja keine Mehrarbeit. Bei manchen Dingen fragt man sich einfach nicht ob mans braucht, man weis genau es ist gut wenn mans hat. Braucht man ein Auto? Ne, aber ist nicht schlecht wenn man eines hat weil man flexibler ist. Aber ja.
